export const GET_PRACTITIONER_QUESTIONNAIRES = "GET_PRACTITIONER_QUESTIONNAIRES";
export const SAVE_PRACTITIONER_QUESTIONNAIRE = "SAVE_PRACTITIONER_QUESTIONNAIRE";
export const DELETE_QUESTIONNAIRE = "DELETE_QUESTIONNAIRE";
export const ASSIGN_QUESTIONNAIRE = "ASSIGN_QUESTIONNAIRE";
export const GET_CLIENTS = "GET_CLIENTS";
export const GET_CLIENT_RESPONSES = "GET_CLIENT_RESPONSES";
