export const GET_QUESTIONNAIRES = "GET_QUESTIONNAIRES";
export const SAVE_QUESTIONNAIRE = "SAVE_QUESTIONNAIRE";
export const DELETE_QUESTIONNAIRE = "DELETE_QUESTIONNAIRE";
export const ASSIGN_QUESTIONNAIRE = "ASSIGN_QUESTIONNAIRE";
export const GET_CLIENTS = "GET_CLIENTS";
